### ISSUE TITLE
Build out framework for documentation in Github wiki

### ISSUE THREAD

**Issue by i-vii-vi** [aecelectronics/public-test#1]

**Comment by Sekramo13** [comment]
I think we've established that GitHub wiki will work well with discussions.
Maybe we can use the foundation doc -> discussions -> wiki pages as more of the "TODO" of this ticket?

**Comment by i-vii-vi** [comment]
Yes, @Sekramo13, I agree entirely. I shall start building out the topics.

**Comment by i-vii-vi** [comment]
I have built out the framework for the documentation that we need on GitHub; however, I am keeping it offline until we have access to Wikis and Discussions on our private repositories. It is information that I feel in appropriate to put on a publicly-accessible repo.
